# Full CI/CD Pipeline with Auto-Tagging Example
# Place this file in .github/workflows/full-ci-cd.yml in your Go project

name: Full CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: "1.21"
  APP_NAME: "my-application"

jobs:
  lint:
    name: Code Quality
    uses: Gosayram/go-release-actions/.github/workflows/lint.yml@main
    with:
      go-version: ${{ env.GO_VERSION }}
      fail-on-warnings: false

  security:
    name: Security Analysis
    uses: Gosayram/go-release-actions/.github/workflows/security-scan.yml@main
    with:
      go-version: ${{ env.GO_VERSION }}
      fail-on-vulnerability: false

  matrix-test:
    name: Matrix Testing
    uses: Gosayram/go-release-actions/.github/workflows/matrix-test.yml@main
    with:
      go-versions: '["1.20", "1.21", "1.22"]'
      operating-systems: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      enable-race-detection: true
      enable-benchmarks: true

  build-test:
    name: Build and Test
    needs: [lint]
    uses: Gosayram/go-release-actions/.github/workflows/build-and-test.yml@main
    with:
      go-version: ${{ env.GO_VERSION }}
      test-timeout: "10m"
      enable-coverage: true
      coverage-threshold: 80

  auto-tag:
    name: Auto Tagging
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [build-test, matrix-test, security]
    uses: Gosayram/go-release-actions/.github/workflows/auto-tag.yml@main
    with:
      version-file: ".release-version"
      tag-prefix: "v"
      branch: "main"
      create-release: false
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

  release:
    name: Create Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-test, matrix-test, security]
    uses: Gosayram/go-release-actions/.github/workflows/release.yml@main
    with:
      go-version: ${{ env.GO_VERSION }}
      app-name: ${{ env.APP_NAME }}
      build-platforms: '["linux/amd64", "linux/arm64", "darwin/amd64", "darwin/arm64", "windows/amd64"]'
      enable-checksums: true
      create-release: true
      prerelease: false
      draft: false
    secrets:
      release-token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      actions: read 