# Simple CI Pipeline Example
# Place this file in .github/workflows/ci.yml in your Go project

name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Code Quality Check
    uses: Gosayram/go-release-actions/.github/workflows/lint.yml@main
    with:
      go-version: "1.21"
      fail-on-warnings: false

  test:
    name: Build and Test
    needs: lint
    uses: Gosayram/go-release-actions/.github/workflows/build-and-test.yml@main
    with:
      go-version: "1.21"
      coverage-threshold: 75
      enable-coverage: true

  security:
    name: Security Scan
    if: github.event_name != 'pull_request'
    uses: Gosayram/go-release-actions/.github/workflows/security-scan.yml@main
    with:
      go-version: "1.21"
      fail-on-vulnerability: false 